version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "webhook-helloworld"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-3cvyxv5y3awt"
s3_prefix = "webhook-helloworld"
region = "ap-southeast-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
